import type { Metadata } from "next";
import "./globals.css";
import { Nunito, Roboto } from "next/font/google";


const nunito = Nunito({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
});

const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${nunito.className} ${roboto.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
